### ISSUE TITLE
Set up react static site

### ISSUE THREAD

**Issue by suraj-swarnapuri** [suraj-swarnapuri/pic-stream#1]
## Description:

set up a stand-alone react web page to display text elements

### Acceptance Criteria:

- [x] install react
- [x] spin up a webpage with text

### Validation:

- [x] pass all unit tests
- [x] screen shot of page on the browser

**Comment by Cmandapat** [comment]
![chrome_2022-03-16_15-55-15](https://user-images.githubusercontent.com/12875810/158689427-68d7b4f3-d97f-41cb-8611-8394e647036a.png)

Initialized react project.
Pushed into 'react-frontend' branch
